### ISSUE TITLE
AmusingKeypadV3 stuck on "device linking"

### ISSUE THREAD

**Issue by iceyrazor** [Antecer/antecer.github.io#7]
hi, ive had this osu! nono since for about 2-3 years now. sadly though on one of the brown keys the pin is broke. but i play to buy a fresh one anyway. 
anyways the latest software does not work with this old one. its just stuck on "device linking"

im not using any usb extenders and its plugged right into a usb 3.0 port.

edit: none of the older versions work. 2.0.0.1-2.0.1.5

**Comment by Antecer** [comment]
Yes, you can get it here:
https://discord.com/invite/3PVnNGu

开 2021/07/20, 星期二 3:32:32, iceyrazor ***@***.***> 写到:
hi, ive had this osu! nono since for about 3-4 years now. and the latest software does not work with this old one. its just stuck on "device linking"
im not using any usb extenders and its plugged right into a usb 3.0 port.
could you kindly release the older version of the software if you still have it?
